# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('cat_image', models.ImageField(null=True, upload_to='cat_image/')),
            ],
        ),
    ]
