# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190107_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
