# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190110_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='auction',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
    ]
