# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190115_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='instruments',
        ),
        migrations.AddField(
            model_name='favourite',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='app.Instrument'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userre', to='app.AppUser'),
        ),
    ]
