# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190217_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bid_amount',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to='app.AppUser'),
        ),
    ]
