# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190222_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='contactlist',
            field=models.ManyToManyField(null=True, related_name='_appuser_contactlist_+', to='app.AppUser'),
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='contact',
        ),
        migrations.AddField(
            model_name='appuser',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
    ]
